AppBundle\Entity\Image:
    type: entity
    table: image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date:
            type: date
        url:
            type: string
            length: 255
        provider:
            type: string
            length: 255
        providerId:
            type: string
            length: 255
        ownerId:
            type: string
            length: 255
        title:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
    indexes:
        provider_ownerId_idx:
            columns: [ provider, ownerId ]
        date_idx:
            columns: [ date ]
    uniqueConstraints:
        provider_providerId_idx:
            columns: [ provider, providerId ]
